# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x07greeter\"(\n\x0bMessageData\x12\x0b\n\x03msg\x18\x01 \x01(\t\x12\x0c\n\x04uuid\x18\x02 \x01(\t\"\x07\n\x05\x45mpty\"\x15\n\x06Status\x12\x0b\n\x03msg\x18\x01 \x01(\t\".\n\x08\x44\x61tabase\x12\"\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x14.greeter.MessageData2m\n\x0eLoggingService\x12-\n\x04Send\x12\x14.greeter.MessageData\x1a\x0f.greeter.Status\x12,\n\x07getData\x12\x0e.greeter.Empty\x1a\x11.greeter.Database2<\n\x0eMessageService\x12*\n\x07getData\x12\x0e.greeter.Empty\x1a\x0f.greeter.Statusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGEDATA']._serialized_start=26
  _globals['_MESSAGEDATA']._serialized_end=66
  _globals['_EMPTY']._serialized_start=68
  _globals['_EMPTY']._serialized_end=75
  _globals['_STATUS']._serialized_start=77
  _globals['_STATUS']._serialized_end=98
  _globals['_DATABASE']._serialized_start=100
  _globals['_DATABASE']._serialized_end=146
  _globals['_LOGGINGSERVICE']._serialized_start=148
  _globals['_LOGGINGSERVICE']._serialized_end=257
  _globals['_MESSAGESERVICE']._serialized_start=259
  _globals['_MESSAGESERVICE']._serialized_end=319
# @@protoc_insertion_point(module_scope)
